"""Brainstem: body-state from the frozen forward, and a law on the stride.

Channels, in order: prediction error, confidence, compute load, surprise,
energy budget. Values are readings. They are not generated by the head.
"""

from __future__ import annotations

import mlx.core as mx

INTERO_DIM = 5
NAMES = ("error", "confidence", "load", "surprise", "energy")


def from_logits(
    logits: mx.array,
    *,
    frac: mx.array,
    true_ids: mx.array | None = None,
) -> mx.array:
    """Build [..., 5] interoception from logits at the current step.

    `frac` is compute used in [0, 1] (thought index / span, or i/K).
    `true_ids` is the next token when known (training); else surprise is
    -max logp.
    """
    logp = logits - mx.logsumexp(logits, axis=-1, keepdims=True)
    entropy = -(mx.exp(logp) * logp).sum(axis=-1)
    vocab = mx.array(logits.shape[-1], dtype=logits.dtype)
    conf = 1.0 - entropy / mx.log(vocab)
    if true_ids is not None:
        gathered = mx.take_along_axis(logp, true_ids.reshape((-1, 1)), axis=-1)
        surprise = -gathered.reshape(true_ids.shape)
        err = surprise
    else:
        surprise = -mx.max(logp, axis=-1)
        err = surprise
    load = frac.astype(logits.dtype)
    energy = (1.0 - frac).astype(logits.dtype)
    return mx.stack([err, conf, load, surprise, energy], axis=-1)


def regulate(delta: mx.array, intero: mx.array) -> tuple[mx.array, mx.array]:
    """High error shrinks the displacement; low error lengthens it."""
    err = intero[..., 0:1]
    scale = 0.35 + 1.30 * mx.sigmoid(-err)
    return delta * scale, scale
